version: '3'

services:
  datascience-notebook:
    user: root
    hostname: 'datascience-notebook'
    image: 'jupyter/datascience-notebook:2ce7c06a61a1'
    command: ['/usr/local/bin/start-notebook.sh', '--NotebookApp.token=']
    environment:
      TZ: "/usr/share/zoneinfo/Australia/Melbourne"
      NB_USER: "${USER}"
      CHOWN_HOME: "yes"
      GRANT_SUDO: "yes"
    volumes:
    - ${WORKSPACE_ROOT_DIR}/notebooks:/home/${USER}
    ports:
    - "8888:8888"

  db:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: "${USER}"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "datalab"
    volumes:
      - ${WORKSPACE_ROOT_DIR}/data/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:2.1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${USER}"
      PGADMIN_DEFAULT_PASSWORD: "password"
    volumes:
    - ${WORKSPACE_ROOT_DIR}/data/postgresql/pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
